name: action
on:
  push:
    branches: 
    - master
  schedule:
    - cron: '20 1 1 1-12 *'

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: update latest arabic data
        run: curl -o "./data/_arabic.json" "https://mp3quran.net/api/v3/reciters?language=ar"
      - name: update latest english data
        run: curl -o "./data/_english.json" "https://mp3quran.net/api/v3/reciters?language=eng"
      - name: push changes
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{secrets.G_TOKEN}}
      
