name: action
on:
  push:
    branches: 
    - master
  schedule:
    - cron: '20 1 1 1-12 *'

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: update latest arabic data
        run: ls
      - name: update latest arabic data
        run: curl -o "./data/_arabic.json" "https://mp3quran.net/api/v3/reciters?language=ar"
      - run: ls ./data
      - name: save changes
        uses: mikael/publish-to-github-actions@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
