name: main action
on:
  schedule:
    - cron: '0/5 * * * *'

jobs:
  test_schedule_0:
    permissions:
      contents: read #write
    runs-on: ubuntu-latest
    steps:
      - name: get latest data
      #  run: echo "getting data..." && curl "http://example.com" -o "/tmp/ar.txt" && cat "/tmp/ar.txt"
        run: echo "$(ls)"
      - name: ls 2
        run: echo "$(ls ${{ github.workspace }})"
      - name: update local data
        run: echo "updating data!"
      #- name: Every time
      #  run: echo "This step will always run"
